### ISSUE TITLE
Há possibilidade de adcionar mais controles do veículo no Home Assistant?

### ISSUE THREAD

**Issue by damiaorocha** [havaleiros/hassio-haval-h6-to-mqtt#4]
Primeiro quero parabenizar e agradecer pelo projeto incrível. Graças a esse projeto consigo pedir para a alexa ligar o ar-condicionado do carro ou acionar com um simples toque no meu galaxy watch6, o que é muito útil.

Sugiro verificar a possibilidade de adicionar mais controles ao home assistant tais como travar e destravar, fechar vidros, teto solar, porta malas.

Com a possibilidade de travar/destravar, poderíamos ter uma automação para quando o smartphone se desconectar do haval por um determinado tempo, travar automaticamente.

**Comment by carvalr** [comment]
Obrigado. Este é um esforço coletivo da comunidade.
Além do comando de ar condicionado, não há planos de adicionarmos mais comandos.
Isto é para evitar competição com o app My GWM. Este deve continuar como o principal app para controle do carro.

Teremos isto em nossa skill Alexa, que será disponibilizada em breve por assinatura.
